---
title: "Lab 3 Warmup"
date: "`r Sys.Date()`"
output: md_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Warm-up

1. Build a vector that includes the following height measurements for five plants:
plant 1 30.7, plant 2 37.6, plant 3 28.4, plant 4 NA, plant 5 33.2

```{r}
height <- c(30.7, 37.6, 28.4, NA, 33.2)
height
```

2. Build another vector that includes the following mass measurements:
plant 1 4, plant 2 5.2, plant 3 3.7, plant 4 NA, plant 5 4.6

```{r}
mass <- c(4, 5.2, 3.7, NA, 4.6)
mass
```

3. Assemble these vectors into a labeled data matrix with two columns

```{r}
plant_data <- cbind(height, mass)
colnames(plant_data) <- c("height", "mass")
plant_data
```

4. Calculate the mean for height and mass and add them to the data matrix

```{r}
mean_height <- mean(height, na.rm = TRUE)
mean_mass <- mean(mass, na.rm = TRUE)
mean_data <- c(mean_height, mean_mass)
```

```{r}
plant_data <- rbind(plant_data, mean_data)
rownames(plant_data)[6] <- "mean"
plant_data
```