---
title: "Lab 5 Warm up"
date: "`r Sys.Date()`"
output: md_document
---


### 1. Load the bison data.

```{r}
library(tidyverse)
bison <- read_csv("data/bison.csv")
bison$animal_sex <- as.factor(bison$animal_sex)
```

### 2. What are the dimesions and structure of the data?

```{r}
dim(bison)
```

### 3. We are only interested in code, sex, weight, year of birth. Restrict the data to these variables and store the dataframe as a new object.

```{r}
names(bison)
```

```{r}
bison_interest <- bison %>% select(animal_code, animal_sex, animal_weight, animal_yob)
head(bison_interest)
```

### 4. Pull out the animals born between 1980-1990.

```{r}
bison_interest_btwn8090 <- bison_interest %>% filter(animal_yob >= 1980 & animal_yob <= 1990)
head(bison_interest_btwn8090)
dim(bison_interest_btwn8090)
```

### 5. How many male and female bison are represented between 1980-1990?

```{r}
table(bison_interest_btwn8090$animal_sex)
```

### 6. Between 1980-1990, were males or females larger on average?

```{r}
anyNA(bison_interest_btwn8090$animal_weight)
```

```{r}
bison_interest_btwn8090[bison_interest_btwn8090$animal_sex=="M", ]$animal_weight %>% mean
bison_interest_btwn8090[bison_interest_btwn8090$animal_sex=="F", ]$animal_weight %>% mean
```
